name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  PGDATABASE: ${{ secrets.PGDATABASE }}
  PGUSER: ${{ secrets.PGUSER }}
  PGPORT: ${{ secrets.PGPORT }}
  PGHOST: ${{ secrets.PGHOST }}
  PGPASSWORD: ${{ secrets.PGPASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npx vitest run
      
    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
        
  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Replit
      env:
        REPLIT_DEPLOY_TOKEN: ${{ secrets.REPLIT_DEPLOY_TOKEN }}
      run: |
        if [ -n "$REPLIT_DEPLOY_TOKEN" ]; then
          echo "Triggering Replit deployment..."
          curl -X POST "https://api.replit.com/v1/deployments/trigger" \
            -H "Authorization: Bearer $REPLIT_DEPLOY_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"sourceRepoUrl": "'"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"'", "gitRef": "'"$GITHUB_SHA"'"}'
        else
          echo "REPLIT_DEPLOY_TOKEN not set. Skipping deployment."
          exit 1
        fi
